### ISSUE TITLE
Javascript package includes python resource description?

### ISSUE THREAD

**Issue by crazyrabbitLTC** [e2b-dev/mcp-server#2]
In checking the code, I noticed that the JS package the tool resource description states that it's designed for Python Code. I assume that's a bug?

See:

 tools: [
        {
          name: "run_code",
          description:
            "Run python code in a secure sandbox by E2B. Using the Jupyter Notebook syntax.",
          inputSchema: zodToJsonSchema(toolSchema),
        },
      ],
    }));

**Comment by mishushakov** [comment]
Everything is correct here. The code interpreter runs Python code.
